--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 17.2

-- Started on 2025-04-22 17:55:48

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 12 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3648 (class 0 OID 0)
-- Dependencies: 12
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 271 (class 1259 OID 17276)
-- Name: entrenador; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.entrenador (
    id_entrenador integer NOT NULL,
    especialidad character varying(255),
    nombre character varying(255),
    id_equipo integer
);


ALTER TABLE public.entrenador OWNER TO postgres;

--
-- TOC entry 270 (class 1259 OID 17275)
-- Name: entrenador_id_entrenador_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.entrenador ALTER COLUMN id_entrenador ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entrenador_id_entrenador_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 273 (class 1259 OID 17284)
-- Name: equipo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.equipo (
    id_equipo integer NOT NULL,
    ciudad character varying(255),
    fundacion date,
    nombre character varying(255)
);


ALTER TABLE public.equipo OWNER TO postgres;

--
-- TOC entry 272 (class 1259 OID 17283)
-- Name: equipo_id_equipo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.equipo ALTER COLUMN id_equipo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipo_id_equipo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 269 (class 1259 OID 17268)
-- Name: estadisticas_jugador; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estadisticas_jugador (
    id_equipo integer NOT NULL,
    ciudad character varying(255),
    fundacion date,
    nombre character varying(255),
    id_estadistica integer NOT NULL,
    asistencias integer NOT NULL,
    goles integer NOT NULL,
    minutos_jugados integer NOT NULL,
    tarjetas_amarillas integer NOT NULL,
    tarjetas_rojas integer NOT NULL,
    id_jugador integer,
    id_oartido integer
);


ALTER TABLE public.estadisticas_jugador OWNER TO postgres;

--
-- TOC entry 268 (class 1259 OID 17267)
-- Name: estadisticas_jugador_id_equipo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.estadisticas_jugador ALTER COLUMN id_equipo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estadisticas_jugador_id_equipo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 274 (class 1259 OID 17291)
-- Name: estadisticas_jugador_id_estadistica_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.estadisticas_jugador ALTER COLUMN id_estadistica ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estadisticas_jugador_id_estadistica_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 276 (class 1259 OID 17299)
-- Name: jugador; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jugador (
    id_jugador integer NOT NULL,
    dorsal integer NOT NULL,
    fecha_nac date,
    nacionalidad character varying(255),
    nombre character varying(255),
    posicion character varying(255),
    id_equipo integer
);


ALTER TABLE public.jugador OWNER TO postgres;

--
-- TOC entry 275 (class 1259 OID 17298)
-- Name: jugador_id_jugador_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.jugador ALTER COLUMN id_jugador ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jugador_id_jugador_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 278 (class 1259 OID 17381)
-- Name: partido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partido (
    id_partido integer NOT NULL,
    estadio character varying(255),
    fecha date,
    goles_local integer NOT NULL,
    goles_visita integer NOT NULL,
    equipo_local integer,
    equipo_visita integer
);


ALTER TABLE public.partido OWNER TO postgres;

--
-- TOC entry 277 (class 1259 OID 17380)
-- Name: partido_id_partido_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.partido ALTER COLUMN id_partido ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partido_id_partido_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3484 (class 2606 OID 17282)
-- Name: entrenador entrenador_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entrenador
    ADD CONSTRAINT entrenador_pkey PRIMARY KEY (id_entrenador);


--
-- TOC entry 3486 (class 2606 OID 17290)
-- Name: equipo equipo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipo
    ADD CONSTRAINT equipo_pkey PRIMARY KEY (id_equipo);


--
-- TOC entry 3482 (class 2606 OID 17274)
-- Name: estadisticas_jugador estadisticas_jugador_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estadisticas_jugador
    ADD CONSTRAINT estadisticas_jugador_pkey PRIMARY KEY (id_equipo);


--
-- TOC entry 3488 (class 2606 OID 17305)
-- Name: jugador jugador_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jugador
    ADD CONSTRAINT jugador_pkey PRIMARY KEY (id_jugador);


--
-- TOC entry 3490 (class 2606 OID 17385)
-- Name: partido partido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partido
    ADD CONSTRAINT partido_pkey PRIMARY KEY (id_partido);


--
-- TOC entry 3495 (class 2606 OID 17386)
-- Name: partido fk1q3nbh68hi4xmjtvh8kp65mw1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partido
    ADD CONSTRAINT fk1q3nbh68hi4xmjtvh8kp65mw1 FOREIGN KEY (equipo_local) REFERENCES public.equipo(id_equipo);


--
-- TOC entry 3491 (class 2606 OID 17396)
-- Name: estadisticas_jugador fkf2qbhoo8qtj60gbvsfrqablkj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estadisticas_jugador
    ADD CONSTRAINT fkf2qbhoo8qtj60gbvsfrqablkj FOREIGN KEY (id_jugador) REFERENCES public.jugador(id_jugador);


--
-- TOC entry 3493 (class 2606 OID 17317)
-- Name: entrenador fkg82oo5rvhpeu6edjri36kjgkl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entrenador
    ADD CONSTRAINT fkg82oo5rvhpeu6edjri36kjgkl FOREIGN KEY (id_equipo) REFERENCES public.equipo(id_equipo);


--
-- TOC entry 3494 (class 2606 OID 17312)
-- Name: jugador fki60lqb7emposedyui33q42u1i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jugador
    ADD CONSTRAINT fki60lqb7emposedyui33q42u1i FOREIGN KEY (id_equipo) REFERENCES public.equipo(id_equipo);


--
-- TOC entry 3492 (class 2606 OID 17401)
-- Name: estadisticas_jugador fkjvq1xn4wvmv6urbr0h047br9u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estadisticas_jugador
    ADD CONSTRAINT fkjvq1xn4wvmv6urbr0h047br9u FOREIGN KEY (id_oartido) REFERENCES public.partido(id_partido);


--
-- TOC entry 3496 (class 2606 OID 17391)
-- Name: partido fkp3l4xr7d0ieyxxk9gp6iyo4sj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partido
    ADD CONSTRAINT fkp3l4xr7d0ieyxxk9gp6iyo4sj FOREIGN KEY (equipo_visita) REFERENCES public.equipo(id_equipo);


--
-- TOC entry 3649 (class 0 OID 0)
-- Dependencies: 12
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- TOC entry 3650 (class 0 OID 0)
-- Dependencies: 271
-- Name: TABLE entrenador; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.entrenador TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.entrenador TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.entrenador TO service_role;


--
-- TOC entry 3651 (class 0 OID 0)
-- Dependencies: 270
-- Name: SEQUENCE entrenador_id_entrenador_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.entrenador_id_entrenador_seq TO anon;
GRANT ALL ON SEQUENCE public.entrenador_id_entrenador_seq TO authenticated;
GRANT ALL ON SEQUENCE public.entrenador_id_entrenador_seq TO service_role;


--
-- TOC entry 3652 (class 0 OID 0)
-- Dependencies: 273
-- Name: TABLE equipo; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.equipo TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.equipo TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.equipo TO service_role;


--
-- TOC entry 3653 (class 0 OID 0)
-- Dependencies: 272
-- Name: SEQUENCE equipo_id_equipo_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.equipo_id_equipo_seq TO anon;
GRANT ALL ON SEQUENCE public.equipo_id_equipo_seq TO authenticated;
GRANT ALL ON SEQUENCE public.equipo_id_equipo_seq TO service_role;


--
-- TOC entry 3654 (class 0 OID 0)
-- Dependencies: 269
-- Name: TABLE estadisticas_jugador; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.estadisticas_jugador TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.estadisticas_jugador TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.estadisticas_jugador TO service_role;


--
-- TOC entry 3655 (class 0 OID 0)
-- Dependencies: 268
-- Name: SEQUENCE estadisticas_jugador_id_equipo_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.estadisticas_jugador_id_equipo_seq TO anon;
GRANT ALL ON SEQUENCE public.estadisticas_jugador_id_equipo_seq TO authenticated;
GRANT ALL ON SEQUENCE public.estadisticas_jugador_id_equipo_seq TO service_role;


--
-- TOC entry 3656 (class 0 OID 0)
-- Dependencies: 274
-- Name: SEQUENCE estadisticas_jugador_id_estadistica_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.estadisticas_jugador_id_estadistica_seq TO anon;
GRANT ALL ON SEQUENCE public.estadisticas_jugador_id_estadistica_seq TO authenticated;
GRANT ALL ON SEQUENCE public.estadisticas_jugador_id_estadistica_seq TO service_role;


--
-- TOC entry 3657 (class 0 OID 0)
-- Dependencies: 276
-- Name: TABLE jugador; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.jugador TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.jugador TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.jugador TO service_role;


--
-- TOC entry 3658 (class 0 OID 0)
-- Dependencies: 275
-- Name: SEQUENCE jugador_id_jugador_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.jugador_id_jugador_seq TO anon;
GRANT ALL ON SEQUENCE public.jugador_id_jugador_seq TO authenticated;
GRANT ALL ON SEQUENCE public.jugador_id_jugador_seq TO service_role;


--
-- TOC entry 3659 (class 0 OID 0)
-- Dependencies: 278
-- Name: TABLE partido; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.partido TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.partido TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.partido TO service_role;


--
-- TOC entry 3660 (class 0 OID 0)
-- Dependencies: 277
-- Name: SEQUENCE partido_id_partido_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.partido_id_partido_seq TO anon;
GRANT ALL ON SEQUENCE public.partido_id_partido_seq TO authenticated;
GRANT ALL ON SEQUENCE public.partido_id_partido_seq TO service_role;


--
-- TOC entry 2288 (class 826 OID 16484)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- TOC entry 2289 (class 826 OID 16485)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- TOC entry 2287 (class 826 OID 16483)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- TOC entry 2291 (class 826 OID 16487)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- TOC entry 2286 (class 826 OID 16482)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO service_role;


--
-- TOC entry 2290 (class 826 OID 16486)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO service_role;


-- Completed on 2025-04-22 17:55:57

--
-- PostgreSQL database dump complete
--

